crop_box_filter:
  ros__parameters:
    input_frame: world
    output_frame: world
    input_pointcloud_frame: rslidar
    max_queue_size: 5
    min_x: -2.0
    min_y: -8.0
    min_z: -1.0
    max_x: 12.0
    max_y: 8.0
    max_z: 6.0
    # Keep points inside the work box.
    negative: false

